apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'gatekeeper'
spec:
  project: default
  sources:
  - repoURL: 'git@github.com:silveraignacio/argocd-apps.git'
    ref: values
  - repoURL: 'https://open-policy-agent.github.io/gatekeeper/charts'
    targetRevision: 3.12.0
    chart: gatekeeper
    helm:
      valueFiles:
      - $values/values/gatekeeper.yaml
  - repoURL: 'git@github.com:silveraignacio/argocd-apps.git'
    path: gatekeeper-base
  - repoURL: 'git@github.com:silveraignacio/argocd-apps.git'
    path: gatekeeper-env-configs/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
