apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'prometheus-monitoring'
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 48.3.1
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/values/prometheus.yaml
  - repoURL: git@github.com:silveraignacio/argocd-apps.git
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
