apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-exporter
spec:
  source:
    repoURL: 'https://github.com/silveraignacio/argocd-apps.git'
    targetRevision: HEAD
    path: root-apps/opa-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
